### ISSUE TITLE
UnicodeEncodeError trying to install pipx to docker container

### ISSUE THREAD

**Issue by guykisel** [cs01/pipx#27]
I'm trying to install pipx into a centos-based docker container. I'm getting an odd error. I'm still poking around myself to try to understand this, but figured I'd also report here in case this is a known issue with a known solution :)

```
Step 83/83 : RUN curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3.6
 ---> Running in 1c48d64c3bc3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6918  100  6918    0     0  24853      0 --:--:-- --:--:-- --:--:-- 24884
Installing pipx
Traceback (most recent call last):
  File "<stdin>", line 231, in <module>
  File "<stdin>", line 228, in main
UnicodeEncodeError: 'ascii' codec can't encode character '\u2728' in position 7: ordinal not in range(128)

============================================================

Note:
  To finish installation, /root/.local/bin must be added to your PATH.
  This can be done by adding the following line to your shell
  config file:

  export PATH=/root/.local/bin:$PATH

============================================================


Now that pipx is installed, we suggest you run one of these commands.

  pipx BINARY [BINARY ARGS ...] #  i.e. pipx cowsay moo

  pipx install PACKAGE  # i.e. pipx install cowsay

  pipx --help  # to see options

Questions or comments? See https://github.com/cs01/pipx
The command '/bin/sh -c curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3.6' returned a non-zero code: 1
```

**Comment by guykisel** [comment]
I think it's actually failing on `print("Enjoy! ✨ 🌟 ✨")`

**Comment by guykisel** [comment]
resolved! needed to add `ENV PYTHONIOENCODING=utf-8`

**Comment by cs01** [comment]
Nice!
