### ISSUE TITLE
can pipx install from local folder/whl/tar.gz?

### ISSUE THREAD

**Issue by tkossak** [cs01/pipx#6]
Is it possible to install package (with all its entry points) that exists only on my hard drive?

```
pipx install '/tmp/3/kossak_cli_tools'
Traceback (most recent call last):
  File "/home/kossak/.local/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.0.0.5', 'console_scripts', 'pipx')()
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 567, in cli
    run_pipx_command(args)
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 358, in run_pipx_command
    install(venv_dir, package, package_or_url, local_bin_dir, args.python, verbose)
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 277, in install
    venv.install_package(package_or_url)
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 78, in install_package
    self._run_pip(["install", package_or_url])
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 145, in _run_pip
    return _run(cmd)
  File "/home/kossak/.local/pipx/venvs/pipx/lib/python3.6/site-packages/pipx/main.py", line 151, in _run
    returncode = subprocess.run(cmd).returncode
  File "/home/kossak/.asdf/installs/python/3.6.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/kossak/.asdf/installs/python/3.6.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/kossak/.asdf/installs/python/3.6.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/tmp/3/kossak_cli_tools/bin/pip'): PosixPath('/tmp/3/kossak_cli_tools/bin/pip')

```

I can do it using pipsi with `pipsi install '/tmp/3/kossak_cli_tools'` and it processes the `setup.py` from this folder properly.

**Comment by cs01** [comment]
You should be able to do something like `pipx install --spec /tmp/3/kossak_cli_tools <package name>`

**Comment by tkossak** [comment]
Doesn't work:

```
> pipx install --spec /tmp/3/kossak_cli_tools kossak_cli_tools
Url was not a valid url
```

**Comment by cs01** [comment]
Sorry about that, thanks for reporting these! I just updated to v 0.0.0.7, try
```
pipx upgrade pipx
```
then try 
```
pipx install --spec /tmp/3/kossak_cli_tools kossak_cli_tools
```
again

**Comment by tkossak** [comment]
```
> pipx upgrade pipx                                                              2 
using url git+https://github.com/cs01/pipx.git for pipx installation
upgraded package pipx to latest version (location: /home/kossak/.local/pipx/venvs/pipx)
> pipx --version
0.0.0.7
> pipx install --spec /tmp/3/kossak_cli_tools kossak_cli_tools
No binaries associated with this package
```

When i install it with pipsi I have:

```
> pipsi install /tmp/3/kossak_cli_tools                                          1 
Processing ./3/kossak_cli_tools
  Installing build dependencies ... done
Collecting click<7.0,>=6.7 (from kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting logzero<2.0,>=1.5 (from kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/97/24/27295d318ea8976b12cf9cc51d82e7c7129220f6a3cc9e3443df3be8afdb/logzero-1.5.0-py2.py3-none-any.whl
Collecting pyperclip<2.0,>=1.6 (from kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Collecting pytaglib<2.0,>=1.4 (from kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/c7/f0/c6d15860c6ab5953320edd36b5050e9d813d025bd49563ef7a24154b69c7/pytaglib-1.4.3.tar.gz
Collecting sh<2.0,>=1.12 (from kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Collecting Cython (from pytaglib<2.0,>=1.4->kossak-cli-tools==0.4.0)
  Using cached https://files.pythonhosted.org/packages/64/3f/cac281f3f019b825bbc03fa8cb7eb03d9c355f4aa9eef978279a4966cb21/Cython-0.29-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: click, logzero, pyperclip, Cython, pytaglib, sh, kossak-cli-tools
  Running setup.py install for pyperclip ... done
  Running setup.py install for pytaglib ... done
  Running setup.py install for kossak-cli-tools ... done
Successfully installed Cython-0.29 click-6.7 kossak-cli-tools-0.4.0 logzero-1.5.0 pyperclip-1.7.0 pytaglib-1.4.3 sh-1.12.14
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  Linked script /home/kossak/.local/bin/capslock_as_escape
  Linked script /home/kossak/.local/bin/capslock_restore
  Linked script /home/kossak/.local/bin/checkeng
  Linked script /home/kossak/.local/bin/countaudio
  Linked script /home/kossak/.local/bin/countextensions
  Linked script /home/kossak/.local/bin/countfiles
  Linked script /home/kossak/.local/bin/e
  Linked script /home/kossak/.local/bin/fix_double_new_lines
  Linked script /home/kossak/.local/bin/ou
  Linked script /home/kossak/.local/bin/replacepolishletters
  Linked script /home/kossak/.local/bin/ytrss
Done.

```

**Comment by cs01** [comment]
Any chance you can share the source of kossak_cli_tools with me?

**Comment by cs01** [comment]
Also you can try 
```
pipx install --verbose --spec /tmp/3/kossak_cli_tools kossak_cli_tools
```
to see if anything else useful is shown.

**Comment by cs01** [comment]
Oh I think I see the error. The package name is `kossak-cli-tools`, so try
```
pipx install --verbose --spec /tmp/3/kossak_cli_tools kossak-cli-tools
```

**Comment by tkossak** [comment]
Now (0.0.0.11) it works with dashes or underscores, thank you!
