### ISSUE TITLE
get-pipx.py fails if ~/.local/pipx does not exist

### ISSUE THREAD

**Issue by neersighted** [cs01/pipx#9]
```
$ curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py -fsSL | python3 - --no-modify-path
Traceback (most recent call last):
  File "<stdin>", line 221, in <module>
  File "<stdin>", line 193, in main
  File "/home/neersighted/.pyenv/versions/3.7.0/lib/python3.7/pathlib.py", line 1230, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/neersighted/.local/pipx/venvs'
```

**Comment by cs01** [comment]
Oh no! Thanks for reporting, I’ll get it fixed.

**Comment by cs01** [comment]
Should  be fixed now. You can try it out with 
```
pipx upgrade pipx
```
